### PR TITLE
add styles dropDown

### PR DESCRIPTION
**Pull request by BrianCortes**

### CODE REVIEW

**Comment by BrianCortes** [comment]
@juniorabranches look this PR ,  only  styles for select  and lack logic for options, I am working in it.
 I am new in react native and I am learning 🥇 
captura de pantalla 2017-10-13 a la s 6 30 37 pm

**Comment by juniorabranches** [comment]
@BrianCortes  very good ...
But how to add options to the select?
Thank you friend

**Comment by BrianCortes** [comment]
@juniorabranches Yea,  in  this weekend I am going to do it  !

**Comment by juniorabranches** [comment]
Great, thank you, my friend.
@BrianCortes see thath #35 👍

**Pull request merged**
